# Generated by Django 5.1.6 on 2025-02-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchLine', models.CharField(max_length=200)),
                ('imageUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
